// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "file": Application User Types
//
// Command:
// $ goagen
// --design=github.com/go-examples/goa/response_file/design
// --out=$(GOPATH)/src/github.com/go-examples/goa/response_file
// --version=v1.2.0-dirty

package app
