basePath: /
definitions:
  account.Account:
    properties:
      email:
        type: string
      id:
        type: string
      password:
        type: string
    type: object
  account.Payload:
    properties:
      email:
        type: string
      id:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server Petstore server.
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: create account
      parameters:
      - description: account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.Payload'
          type: object
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/account.Payload'
            type: object
      summary: Create a account
  /accounts/{id}:
    get:
      consumes:
      - application/json
      description: get account by ID
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.Account'
            type: object
      summary: Show a account
  /hello:
    get:
      consumes:
      - application/json
      description: show hello
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/string'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
            type: object
      summary: hello world
swagger: "2.0"
